# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'STDevTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'RxAlamofire'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.1'
    pod 'AlamofireNetworkActivityIndicator', '~> 2.0'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'ObjectMapper', '~> 2.2'
    pod 'SwiftHEXColors'
    pod 'MisterFusion'

  target 'STDevTemplateTests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.0'
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
  end

  target 'STDevTemplateUITests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.0'
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
  end

end
